config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :rooms
  devise_for :users
  root 'static_pages#landingpage'
  # root 'static_pages#home'
  get 'static_pages/home', as: 'home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'application#hello'
  get '/publications', to: 'publications#index'
  get 'publications/user/:user_id', to: 'publications#owner_publications', as: 'owner_publications'
  get '/publications/new', to: 'publications#new'
  post '/publications', to: 'publications#create'
  get '/publication/:id', to: 'publications#show', as: 'publication'
  get '/publications/:id/edit', to: 'publications#edit', as: 'edit_publication'
  patch '/publication/:id', to: 'publications#update'
  delete '/publication/:id', to: 'publications#delete'

  delete '/user/:id', to: 'users#delete', as: 'delete_user'

  get '/resenas/:user_id', to: 'resenas#index', as: 'user_resenas'
  get '/resenas/show/:user_id', to: 'resenas#show', as: 'show_resenas'
  get '/resenas/new/:user_id', to: 'resenas#new', as: 'new_resena'
  post '/resenas/:user_id', to: 'resenas#create'
  get '/resenas/:id/edit', to: 'resenas#edit', as: 'edit_resena'
  patch '/resena/:id', to: 'resena#update'
  delete '/resena/:id', to: 'resenas#destroy', as: 'destroy_resena'
  patch '/solicituds/:id', to: 'solicituds#approve', as: 'approve_solicitud'
  delete '/solicituds/:id', to: 'solicituds#reject', as: 'reject_solicitud'

  resources :solicituds, only: %i[create destroy index approve reject]

  resources :users
  resources :publications do
    resources :comments
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :publication
  belongs_to :user
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/publication.rb
# frozen_string_literal: true

# Modelo de Publication
class Publication < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :solicituds, dependent: :destroy
  has_one :room, dependent: :destroy
  validates :titulo, length: { minimum: 5 }
  validates :punto_partida, length: {  minimum: 2 }
  validates :punto_llegada, length: {  minimum: 2 }
  # validates :fecha, presence: true
  # validates :cupos, length: { minimum: 10 }
  # validates :radio, length: { minimum: 10 }

  def self.search(search)
    where('comuna_partida LIKE ? OR comuna_llegada LIKE ?', "%#{search}%", "%#{search}%")
  end
end

app/models/request.rb
# frozen_string_literal: true

# validates_uniqueness_of requested_user_id:, scope: :publication_id

class Request < ApplicationRecord
  validates :requested_user_id, uniqueness: { scope: :publication_id }
  belongs_to :user
  belongs_to :publication
end

app/models/resena.rb
# frozen_string_literal: true

class Resena < ApplicationRecord
  belongs_to :user
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :messages
  has_many :users
  belongs_to :publication
end

app/models/solicitud.rb
# frozen_string_literal: true

class Solicitud < ApplicationRecord
  belongs_to :user
  belongs_to :publication
  validates :user, uniqueness: { scope: :publication_id }
end

app/models/user.rb
# frozen_string_literal: true

# Modelo de User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_uniqueness_of :username
  has_many_attached :images, dependent: :destroy
  has_many :publications, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :resenas, dependent: :destroy
  has_many :solicituds
  # validates :name, presence: true, lenght: {maximum: 50}
  validates :name, presence: true, length: { minimum: 2 }
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# Controlador
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @rooms = Room.all
    render 'index'
  end

  # GET /rooms/new
  def new
    @room = Room.new
    render 'index'
  end

  # GET /rooms/1/edit
  def edit; end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper de ApplicationController
module ApplicationHelper
  def render_stars(value)
    output = ''
    value.to_i.times { output += '*' } if (1..5).include?(value.to_i)
    output
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# Comments Helper
module CommentsHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

# Helper
module MessagesHelper
end

app/helpers/publications_helper.rb
# frozen_string_literal: true

# Helper de publicacioes
# module PublicationHelper
# end

# frozen_string_literal: true

# Publications Helper
module PublicationsHelper
  # la primera letra del titulo será mayuscula
  def first_letter(act_title)
    upper_title = act_title.capitalize
    (upper_title == act_title)
  end
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

# Requests Helper
module RequestsHelper
end

app/helpers/resena_helper.rb
# frozen_string_literal: true

# Reseña Helper
module ResenaHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

# Helper
module RoomsHelper
end

app/helpers/solicituds_helper.rb
# frozen_string_literal: true

# Helper de Solicitudes
module SolicitudsHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

# Helper de páginas estáticas
module StaticPagesHelper
end

app/views/shared/_feed.html.erb
<!--Section: Newsfeed-->
<% i = 5 + rand(9)%>

  <div class="test">

  <div class="card" style="max-width: 20rem">
    <div class="card-body">
      <div class="d-flex mb-3"
        <div><h5> Filtrar Publicaciones </h5></div>
        <%= form_tag(publications_path, method: :get) do %>
          <p> Comuna: <%= select_tag(:search, options_for_select(["Cerrillos","Cerro Navia","Conchalí","El Bosque",
          "Estación Central","Huechuraba","Independencia","La Cisterna","La Florida","La Granja","La Pintana","La Reina","Las Condes",
          "Lo Barnechea","Lo Espejo","Lo Prado","Macul","Maipú","Pedro Aguirre Cerda","Peñalolén","Providencia","Pudahuel","Quilicura",
          "Quinta Normal","Recoleta","Renca","San Joaquín","San Miguel","San Ramón","Santiago","Vitacura","Ñuñoa"]), :include_blank => true) %></p>
        <%= submit_tag ("Buscar") %>
      </div>
    </div>
  </div>

<% @publications.each do |publication|%>

  <section>
<br>
<br>
  <div class="card" style="max-width: 42rem">
    <div class="card-body">
      <!-- Data -->
      <div class="d-flex mb-3">
        <a href= <%= user_path(publication.user_id)%> >
        <% if publication.user.images.attached? %>
          <%= image_tag publication.user.images.first, alt:"Avatar", class:"border rounded-circle me-2", style:"height: 40px" %>
        <% else %>
          <img src="https://i.ibb.co/b6zws6y/avatar.webp" class="border rounded-circle me-2" alt="Avatar" style="height: 40px" />
        <% end %>
        </a>
        <div>
          <a href= <%= publication_path(publication)%> class="text-dark mb-0">
            <strong> <%= publication.titulo%> </strong>
          </a>
          <a href="" class="text-muted d-block" style="margin-top: -6px">
            <small> <%= publication.user.username%> </small>
          </a>
        </div>
      </div>
      <!-- Description -->
      <div>
        <p>
        Yo los llevo, mi mail es <%= publication.user.email %> <br>
        Publicación creada el: <%= publication.created_at%> <br>
        Fecha de salida: <%= publication.fecha %> <br>
        Hora de salida: <%= publication.hora %> <br>
        Punto de partida: <%= publication.punto_partida %>, <%= publication.comuna_partida %> <br>
        Punto de llegada: <%= publication.punto_llegada %>, <%= publication.comuna_llegada %> <br>
        Cupos: <%= publication.cupos%> <br>
        Radio max para buscar pasajeros (km): <%= publication.radio%> <br>
        </p>
      </div>
    </div>
        

        <% pic = "https://picsum.photos/seed/" %>
        <% size = "/700/" %>
        <% i += 1 + rand(30)%>
        <% url = pic + i.to_s + size%>
        <% puts url%>
        <% puts url%>
    <!-- Media -->
        
    <!-- Interactions -->
    <div class="card-body">
      <!-- Reactions -->
      <div class="d-flex justify-content-between mb-3">
        <div>
          <a href="">
            <i class="fas fa-thumbs-up text-primary"></i>
            <i class="fas fa-heart text-danger"></i>
          </a>
        </div>
        <div>
          <a href= <%= publication_path(publication)%>   class="text-muted"> <%= publication.comments.count%> comentarios </a>
        </div>
      </div>
      <!-- Reactions -->

      <!-- Buttons -->
      <div class="d-flex justify-content-between text-center mb-4">
          <%= button_to "Ver Publicación", publication_path(publication), type: "button", class: "button button5",  method: :get%>
        <% if current_user == publication.user  %>
          <%= button_to "Editar", edit_publication_path(publication), type: "button", class: "button button5",  method: :get%>
          <% end %>
          <% if current_user == publication.user || current_user.admin == true %>
          <%= button_to "Eliminar", publication, type: "button", class: "button button5", method: :delete, data: { confirm: "Deseas eliminar esta publicación?"} %>
          <% end %>
          <% if current_user != publication.user  %>
            <%= button_to "Solicitar viaje", solicituds_path, type: "button", class: "button button5" ,params: { solicitud: {publication_id: publication.id}}, method: :post%>
            <%= button_to "Dejar Reseña", new_resena_path(publication.user), type: "button", class: "button button5",  method: :get%>
            <% end %>
        
        
      </div>
      <!-- Buttons -->

      <!-- Comments -->

      <!-- Answers -->
      <% i = 0%>
      <% publication.comments.each do |comment|%>
      <% break if (i == 3)%>
      <!-- Single answer -->
        <div class="d-flex mb-3">
            <a href="">
            <% if comment.user.images.attached? %>
              <%= image_tag comment.user.images.first, alt:"Avatar", class:"border rounded-circle me-2", style:"height: 40px" %>
            <% else %>
              <img src="https://i.ibb.co/b6zws6y/avatar.webp" class="border rounded-circle me-2" alt="Avatar" style="height: 40px" />
            <% end %>
            </a>
            <div>
            <div class="bg-light rounded-3 px-3 py-1">
                <a href= <%= user_path(comment.user) %> class="text-dark mb-0">
                <strong> <%= comment.user.email%> </strong>
                </a>
                <a class="text-muted d-block">
                <small> <%= comment.content %> </small>
                </a>
            </div>
            <% if current_user == comment.user %>
              <strong><%= link_to 'Eliminar comentario', [comment.publication, comment], method: :delete, data: { confirm: "Deseas eliminar este comentario?"}, class: "text-muted small ms-3 me-2" %> </strong>
              <strong> <%= link_to 'Editar comentario', edit_publication_comment_path(comment.publication, comment), class: "text-muted small me-2" %> </strong>
            <% end %>
            </div>
        </div>
        <% i += 1 %>
      <% end %>
            <div class="bg-light rounded-3 px-3 py-1">
            </div>
            <div class="bg-light rounded-3 px-3 py-1">
            </div>
            <div class="bg-light rounded-3 px-3 py-1">
            </div>
            <div class="bg-light rounded-3 px-3 py-1">
                <strong> Ingrese a la publicación para comentar o ver más comentarios </strong>
            </div>
      
      

      
      <!-- Single answer -->

      <!-- Answers -->

      <!-- Comments -->
    </div>
    <!-- Interactions -->
  </div>
</section>
<!--Section: Newsfeed-->

<% end %>

<% end %>

app/views/shared/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">© 2022</small>
      </div>
      <div class="col-6 col-md">
        <h5>Integrantes</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://github.com/franciscavelascog">Francisca Velasco</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://github.com/gaboaurora">Gabriel Venegas</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://github.com/antoniadelasotta">Antonia De la Sotta</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Product Owner</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://github.com/mariizamb">Mariela Zambrano</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Acerca de nosotros</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Somos los más bacanes!</a></li>
        </ul>
      </div>
    </div>
  </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
<div class="container-fluid">
  <%= link_to "VIAJES UCÉ", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class=" collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ms-auto ">
      <li class="nav-item">
        <a class="nav-link mx-2 active", <%= link_to "Home", root_path, class: "btn_a" %> </a>
      </li>
      <% if current_user%>
        <li class="nav-item">
          <a class="nav-link font-italic mb-1", <%= link_to "Publicaciones", publications_path, class: "btn_a" %>   </a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-italic mb-1", <%= link_to "Crear Publicación", publications_new_path, method: :get %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-italic mb-1", <%= link_to "Perfiles", users_path, method: :get %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-italic mb-1", <%= link_to "Mi Perfil", user_path(current_user) if current_user%> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-italic mb-1", <%= link_to "Mis solicitudes", solicituds_path, class: "btn_a" %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-italic mb-1", <%= link_to "Mis chats", rooms_path, class: "btn_a" %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-italic mb-1", <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %> </a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link font-italic mb-1", <%= link_to "Iniciar sesión", new_user_session_path, method: :get %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-italic mb-1", <%= link_to "Registrarse", new_user_registration_path, method: :get %> </a>
        </li>
      
      
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Viajes Ucé
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" <%= link_to "Ayuda", static_pages_help_path, method: :get %></li>
          <li><a class="dropdown-item" <%= link_to "Nosotros", static_pages_about_path, method: :get %></li>
          <li><a class="dropdown-item" <%= link_to "Contacto", static_pages_contact_path, method: :get %></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
</nav>