config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :rooms
  devise_for :users
  root 'static_pages#landingpage'
  # root 'static_pages#home'
  get 'static_pages/home', as: 'home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'application#hello'
  get '/publications', to: 'publications#index'
  get 'publications/user/:user_id', to: 'publications#owner_publications', as: 'owner_publications'
  get '/publications/new', to: 'publications#new'
  post '/publications', to: 'publications#create'
  get '/publication/:id', to: 'publications#show', as: 'publication'
  get '/publications/:id/edit', to: 'publications#edit', as: 'edit_publication'
  patch '/publication/:id', to: 'publications#update'
  delete '/publication/:id', to: 'publications#delete'

  delete '/user/:id', to: 'users#delete', as: 'delete_user'

  get '/resenas/:user_id', to: 'resenas#index', as: 'user_resenas'
  get '/resenas/show/:user_id', to: 'resenas#show', as: 'show_resenas'
  get '/resenas/new/:user_id', to: 'resenas#new', as: 'new_resena'
  post '/resenas/:user_id', to: 'resenas#create'
  get '/resenas/:id/edit', to: 'resenas#edit', as: 'edit_resena'
  patch '/resena/:id', to: 'resena#update'
  delete '/resena/:id', to: 'resenas#destroy', as: 'destroy_resena'
  patch '/solicituds/:id', to: 'solicituds#approve', as: 'approve_solicitud'
  delete '/solicituds/:id', to: 'solicituds#reject', as: 'reject_solicitud'

  resources :solicituds, only: %i[create destroy index approve reject]

  resources :users
  resources :publications do
    resources :comments
  end
end

app/models/solicitud.rb
# frozen_string_literal: true

class Solicitud < ApplicationRecord
  belongs_to :user
  belongs_to :publication
  validates :user, uniqueness: { scope: :publication_id }
end

app/controllers/solicituds_controller.rb
# frozen_string_literal: true

# Controlador de solicitudes de viajes
class SolicitudsController < ApplicationController
  before_action :find_publications
  def create
    @solicitud = current_user.solicituds.new(solicitud_params)
    @solicitud.status = 'pending'
    flash[:notice] = 'No se pudo crear la solicitud' unless @solicitud.save
    redirect_to @solicitud.publication
  end

  def destroy
    @solicitud = current_user.solicituds.find(params[:id])
    @publication = solicitud.publication
    @solicitud.destroy
    redirect_to @publication
  end

  def index
    @solicituds = Solicitud.where(publication_id: @publicaciones_propias.ids)
    @users = User.all
    @publications = Publication.all
  end

  def approve
    @solicitud = Solicitud.find(params[:id])
    @solicitud.status = 'approved'
    flash[:notice] = 'No se pudo crear la solicitud' unless @solicitud.save
    redirect_to @solicitud.publication
  end

  def reject
    @solicitud = Solicitud.find(params[:id])
    @solicitud.destroy
    redirect_to publications_path
    flash[:notice] = 'Has rechazado la solicitud'
  end

  private

  def solicitud_params
    params.require(:solicitud).permit(:publication_id)
  end

  def find_publications
    @publicaciones_propias = Publication.where(user_id: current_user.id)
  end
end

app/helpers/solicituds_helper.rb
# frozen_string_literal: true

# Helper de Solicitudes
module SolicitudsHelper
end

app/views/solicituds/index.html.erb
<h1>Mis solicitudes</h1>
<% @solicituds.each do |solicitud|%>
	<% @users.each do |user|%>
		<% @publications.each do |publication|%>
			<% if user.id == solicitud.user_id %>
				<% if solicitud.publication_id == publication.id %>
					<% if solicitud.status == "pending"%>
							<a > <%= user.username %> solicito viajar contigo en la publicación <%= publication.titulo%> </a> <br>
							<%= button_to "Aceptar", approve_solicitud_path(solicitud), type: "button", class: "button button5", method: :patch%>
							<%= button_to "Rechazar", reject_solicitud_path(solicitud), type: "button", class: "button button5", method: :delete, data: { confirm: "Deseas rechazar esta solicitud?"}%>
					<% else %>
						<a> <%= user.username %> solicito viajar contigo en la publicación <%= publication.titulo%> </a> <br>
						<button type="button" class="btn btn-dark" data-mdb-ripple-color="dark"> Ya se acepto esta solicitud </button> <br>

					
					<% end %>
					
				<% end %>
			
			<% end %>
		
		<% end %>
		
	<% end %>
		

<% end %>