config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :rooms
  devise_for :users
  root 'static_pages#landingpage'
  # root 'static_pages#home'
  get 'static_pages/home', as: 'home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'application#hello'
  get '/publications', to: 'publications#index'
  get 'publications/user/:user_id', to: 'publications#owner_publications', as: 'owner_publications'
  get '/publications/new', to: 'publications#new'
  post '/publications', to: 'publications#create'
  get '/publication/:id', to: 'publications#show', as: 'publication'
  get '/publications/:id/edit', to: 'publications#edit', as: 'edit_publication'
  patch '/publication/:id', to: 'publications#update'
  delete '/publication/:id', to: 'publications#delete'

  delete '/user/:id', to: 'users#delete', as: 'delete_user'

  get '/resenas/:user_id', to: 'resenas#index', as: 'user_resenas'
  get '/resenas/show/:user_id', to: 'resenas#show', as: 'show_resenas'
  get '/resenas/new/:user_id', to: 'resenas#new', as: 'new_resena'
  post '/resenas/:user_id', to: 'resenas#create'
  get '/resenas/:id/edit', to: 'resenas#edit', as: 'edit_resena'
  patch '/resena/:id', to: 'resena#update'
  delete '/resena/:id', to: 'resenas#destroy', as: 'destroy_resena'
  patch '/solicituds/:id', to: 'solicituds#approve', as: 'approve_solicitud'
  delete '/solicituds/:id', to: 'solicituds#reject', as: 'reject_solicitud'

  resources :solicituds, only: %i[create destroy index approve reject]

  resources :users
  resources :publications do
    resources :comments
  end
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :messages
  has_many :users
  belongs_to :publication
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# Controlador
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @rooms = Room.all
    render 'index'
  end

  # GET /rooms/new
  def new
    @room = Room.new
    render 'index'
  end

  # GET /rooms/1/edit
  def edit; end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

# Helper
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit "Add room" , class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div id="user-id" data-user-id=" <%= current_user.id %>">    </div>

<h1>Salas</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-3">
      <%=  render 'form', room: Room.new %>
      <hr>
      <% @rooms.each do |room| %>
        <%= link_to room do%>
          <div class="card mb-2">
            <div class="card-body">
              <%= room.name %>
            </div>
          </div>     
        <% end %> 
      <% end %>

    </div>
      <div class="col-9">  
        <% if @room.present? %>
          <div class="chat-room">
            <nav class="navbar-chat navbar-light bg-light mb-4">
              <span class="navbar-brand" href="#"> <%= @room.name%>   
                <ul class='navbar-nav'>
                  <li class='nav-item'>
                    Hola, <%= current_user.username%>
                  </li>
                </ul>
              </span>
            </nav>
            <div id='messages' >
              <% @room.messages.each do |message| %>
                  <%= render 'messages/message', message: message %>
              <% end %>
            </div>
            


            <div class="chat-box">
              <%= render 'messages/form', message: Message.new, room: @room %>
            </div>

          </div>

        <% end %>
      </div>
  </div>

</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>